### ISSUE TITLE
import PDBeMolstarPlugin ?

### ISSUE THREAD

**Issue by iandaaci** [molstar/pdbe-molstar#108]
There are already clear instructions on how to include this as a plugin and web component.
 
I am looking to import `PDBeMolstarPlugin` to the dependencies of an existing (React based) app - would you expect this to be possible?

I have tried:

```
import { PDBeMolstarPlugin } from "pdbe-molstar/lib"
```

However this generates many errors when trying to resolve `Molstar` libraries, e.g:

```
ERROR in ./node_modules/pdbe-molstar/lib/ui/symmetry-annotation-controls.js 13:17-44
Module not found: Error: Can't resolve 'Molstar/mol-task' in '/Users/ian/Documents/GitHub/pdbe-molstar-cra-test/node_modules/pdbe-molstar/lib/ui'
```

(should `Molstar/mol-task` be `molstar/lib/mol-task`?)

Any pointers would be useful

**Comment by midlik** [comment]
Hi, I assume this is an error thrown by Webpack.

As you said, `Molstar` is an alias for `molstar/lib`. Try adding these three line to you Webpack config file: https://github.com/molstar/pdbe-molstar/blob/4805c00b5e3ff2ed112ab7f013a0b4231c0fa36e/webpack.config.production.js#L62-L64
so that it can resolve `Molstar`.

**Comment by sillitoe** [comment]
Hi - great, thanks very much for your help.

The framework I'm using is [Vite](https://vitejs.dev/) which it turns out uses [rollup](https://rollupjs.org/) rather than webpack. 

However, I was able to achieve a similar effect with:

```
# vite.config.ts
export default defineConfig({
  ...
  resolve: {
    alias: {
      'Molstar': 'molstar/lib'
    }
  }
})
```
