### ISSUE TITLE
Show the sequence and make it hoverable

### ISSUE THREAD

**Issue by Firingam** [molstar/pdbe-molstar#62]
Dear all,
I would like to insert Molstar in one web project that exploits custom data, stored locally.
I am studying Wikia (https://github.com/molstar/pdbe-molstar/wiki/1.-PDBe-Molstar-as-JS-plugin_v0.1.0) but currently, I am not finding any solution to show the sequence together with the whole visualizer like in this RCSB [example.](https://www.rcsb.org/3d-view/131D).
Some suggestion?

**Comment by mandarsd** [comment]
Hi,
The sequence section is not used in any of the PDBe pages that's why it is disabled. I'll add a feature requests to add an option to display the sequence section.

Meanwhile, to have an instance with the sequence section, you could fork this repo and comment this line - https://github.com/molstar/pdbe-molstar/blob/master/src/app/index.ts#L112 and build an instance for your use.

**Comment by mandarsd** [comment]
Added `sequencePanel ` parameter to toggle Sequence section display in v3.1.0
